### ISSUE TITLE
ballot positions don't have electiondate field

### ISSUE THREAD

**Issue by eads** [newsdev/elex#210] opened 2016-02-02 22:23 UTC

**Comment by jeremyjbowers** [comment] 2016-02-03 22:03
This is important but no ballot positions on the ballots until March 1. http://customersupport.ap.org/doc/eln/2016_Election_Calendar.pdf

Pushing this ticket to the Super Tuesday milestone.

**Comment by jeremyjbowers** [comment] 2016-02-25 15:59
Actually, neither `Candidate` nor `BallotMeasure` get an `electiondate` field by design. These are supposed to be the fields that could persist past a single election like IDs and names and such. An `electiondate` field provides no more uniqueness than the `unique_id` or `id` fields do.

**Comment by jeremyjbowers** [comment] 2016-02-25 16:00
Moving this to `low` and `decision required` because I don't think this field is actually required on the model object.

**Comment by greglinch** [comment] 2016-02-25 16:23
I'd vote for including electiondate on `BallotMeasure` in cases where uses might want to archive past ballot measures or avoid possible duplication in a database that includes Elex-generated and hand-keyed results.

**Closed** 2016-02-25 17:54 UTC
Labels: decision required, low
